---
title: "simulationStudy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simulationStudy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(repulsiveDimples)
```

We initialize model parameters to be estimated:
```{r parameter_initialisation}
true_phi <- 0.8
true_rho <- 3
true_sigmasq <- 80
true_repulsionRange <- 0.4
kappa <- true_rho^2/(2*pi*true_phi*true_sigmasq)
mu <- 2*pi*true_phi*true_sigmasq/true_rho

true_params <- c(true_phi, true_rho, true_sigmasq, true_repulsionRange, kappa, mu)
setNames(true_params, c("phi", "rho", "sigmasq", "h", "kappa", "mu"))
rm(true_phi, true_rho, true_sigmasq, true_repulsionRange, kappa, mu)

sidelength <- 10
sim_win <- spatstat.geom::owin(xrange = c(0,sidelength),
                yrange = c(0,sidelength))
timescale <- 1 # We simulate independent realizations
```

We simulate a list of point patterns to use:
```{r simulate_pointPatterns}
sim_list <- vector(mode = "list", length = 10)
set.seed(seed = 1349)
for (i in 1:10) {
  sim_single <- rVarGamma_matern_thinned(kappa = true_params[5],
                                         scale = true_params[1],
                                         mu = true_params[6],
                                         nu = -1/4,
                                         repulsionRange = true_params[4],
                                         win = sim_win)
  sim_list[[i]] <- data.frame(x = sim_single$x/sidelength, y = sim_single$y/sidelength)
}
rm(sim_single, i)
```

We estimate the summary statistics for our data:
```{r make_hats}
rho_hat <- intensity_est(points_input = sim_list, l = sidelength, timescale = timescale)
K_hat <- K_est.unions(points_input = sim_list,
                      l = sidelength,
                      timescale = timescale,
                      spacing = 5,
                      rMax = sidelength/2.5,
                      dr = 0.05)

min_dist <- find_min_dist(points_input = sim_list, l = sidelength, timescale = timescale)
```

We run the Minimum Contrast estimation:
```{r optimize}
res <- stats::optim(par = c(1, 1, 1),
                    fn = objective_weighted_contrast_vargamma,
                    rho_hat = rho_hat,
                    K_hat = K_hat,
                    repulsionRange_hat = min_dist,
                    w_rho = 100,
                    q_rho = 1,
                    p_rho = 2,
                    w_K = 2,
                    q_K = 1/4,
                    p_K = 2,
                    union_est = TRUE,
                    win = spatstat.geom::owin(xrange = c(0,10),
                               yrange = c(0,10)),
                    nSims = 20,
                    parallel = FALSE, # Had some issues with the parallel package for vignette building
                    control = list(maxit = 50)) # Maxit set to something low to knit quickly
```

Having ran the estimation, we look at the resulting parameter estimates:
```{r estimates_presentation}
estim_phi <- exp(res$par[1])
estim_rho <- exp(res$par[2])
estim_sigmasq <- exp(res$par[3])
estim_repulsionRange <- min_dist
estim_kappa <- estim_rho^2/(2*pi*estim_phi*estim_sigmasq)
estim_mu <- 2*pi*estim_phi*estim_sigmasq/estim_rho

estim_params <- c(estim_phi, estim_rho, estim_sigmasq, estim_repulsionRange, estim_kappa, estim_mu)
setNames(estim_params, c("phi", "rho", "sigmasq", "h", "kappa", "mu"))
rm(estim_phi, estim_rho, estim_sigmasq, estim_repulsionRange, estim_kappa, estim_mu)
```
















